version: '3.7'

services:
    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/srv/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#        restart: always


    nginx:
        depends_on:
            - php
        image: nginx:alpine
        volumes:
            - ./:/srv/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/skeleton.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 8086:80

    db:
        image: mysql:5.7
        command: "--default-authentication-plugin=mysql_native_password  --disable-partition-engine-check"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        ports:
          - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8087:80"
        links:
            - db

volumes:
    db-data: {}
